logging:
  level:
    root: info

#mybatis-plus映射mapper文件
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  cache:
    type: redis
    redis:
      host: localhost
      lettuce:
        pool:
          max-active: 16
          max-wait: 10ms

  #配置分库分表策略
  shardingsphere:
    datasource:
      common:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
      ds0:
        autoCommit: false
        jdbc-url: jdbc:mysql://localhost:3306/tomato_shop_0?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        password: 123456
        username: root
      ds1:
        autoCommit: false
        jdbc-url: jdbc:mysql://localhost:3306/tomato_shop_1?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        password: 123456
        username: root
      names: ds0,ds1
    rules:
      props:
        sql:
          show: true
      sharding:
        key-generators:
          snowflake:
            props:
              worker-id: 33
            type: snowflake
        sharding-algorithms:
          database-inline:
            props:
              algorithm-expression: ds$->{id % 2}
            type: INLINE
#          table-inline:
#            props:
#              algorithm-expression: ums_member
#            type: INLINE
        tables:
          #由于整合了mybatis-plus，所以这里逻辑表名称改成跟实际表名称一致
          ums_member:
            actual-data-nodes: ds$->{0..1}.ums_member
            database-strategy:
              standard:
                sharding-algorithm-name: database-inline
                sharding-column: id
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
            key-generator:
              column: id
              props:
                worker:
                  id: 33
              type: SNOWFLAKE
#            tale-strategy:
#              standard:
#                sharding-algorithm-name: table-inline
#                sharding-column: id
swagger:
  application-description: Cache Demo Practice
  application-name: Cache Service
  application-version: 1.0
  enable: true
  try-host: http://localhost:${server.port}
