server:
  port: 8083

spring:
  application:
    name: demo-eureka-server

eureka:
  instance:
    prefer-ip-address: false
    hostname: node03
  client:
    serviceUrl:
      defaultZone: http://node01:8081/eureka/,http://node02:8082/eureka/
    #是否将自己注册到Eureka Server
    registerWithEureka: true
    #是否从Eureka Server获取注册信息
    fetchRegistry: true