server:
  port: 8181

spring:
  application:
    name: eureka-client #服务名称

eureka:
  client:
    registerWithEureka: true #注册到Eureka的注册中心
    fetchRegistry: true #获取注册实例列表
    serviceUrl:
      defaultZone: http://node01:8081/eureka/,http://node02:8082/eureka/,http://node03:8083/eureka/ #配置注册中心地址