server:
  port: 8182

spring:
  application:
    name: eureka-client #服务名称

eureka:
  client:
    registerWithEureka: true #注册到Eureka的注册中心
    fetchRegistry: true #获取注册实例列表
    serviceUrl:
      defaultZone: http://nerotomato:123456@localhost:8084/eureka/ #配置需要登录认证的注册中心地址