server:
  port: 8201
spring:
  application:
    name: user-service
eureka:
  client:
    registerWithEureka: true #注册到Eureka的注册中心
    fetchRegistry: true #获取注册实例列表
    serviceUrl:
      #defaultZone: http://node01:8081/eureka/,http://node02:8082/eureka/,http://node03:8083/eureka/ #配置注册中心地址
      defaultZone: http://nerotomato:123456@localhost:8084/eureka/
# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: USER-SERVICE
  application-version: 1.0
  application-description: springfox swagger 3.0整合
  try-host: http://localhost:${server.port}